# port number
server:  port: 9090 
#database confi
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/hellodoctor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name:  HELLO-DOCTOR
#hibernate config
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
     