package com.hellodoctor.constant;

public class Constant {

	public static final String DEFAULT_CONTENT_TYPE = "application/octet-stream";
	public static final String FILE_DOWNLOAD_HTTP_HEADER = "attachment; filename=\"%s\"";
	public static final String DOCTORROLE ="ROLE_DOCTOR"; 
	public static final String PATIENTROLE = "ROLE_PATIENT";
	public static final String EXCEPTION613 ="Something Went Wrong";
	public static final String WELCOME ="Welcome To Hello Doctor";
	public static final String EXCEPTION602 ="Given Information Is Not Valid";
	public static final String EXCEPTION603 ="Something Went Wrong";
	public static final String EXCEPTION601 = "please send the proper information";
	public static final String EXCEPTIONCODE601="601";
	public static final String EXCEPTIONCODE602="602";
	public static final String EXCEPTIONCODE603="603";
	public static final String EXCEPTIONCODE606="606";
	public static final String EXCEPTIONCODE607="607";
	public static final String EXCEPTIONCODE608="608";
	public static final String EXCEPTIONCODE613="613";
	public static final String EXCEPTIONCODE618="618";
	public static final String EXCEPTIONCODE604="604";
	public static final String EXCEPTIONCODE620="620";
	public static final String EXCEPTIONCODE609="609";
	public static final String EXCEPTIONCODE621="621";
	public static final String EXCEPTIONCODE640="640";
	public static final String EXCEPTION606= "Given Id Is Null Please Send Some Id";
	public static final String EXCEPTION607="Please Enter The Valid Id";
	public static final String EXCEPTION608="Something Went Wrong";
	public static final String EXCEPTION618 = "Service Error Problem";
	public static final String EXCEPTION604= "List Is Empty";
	public static final String EXCEPTION620="Please Enter The Valid Email";
	public static final String EXCEPTION621= "Given Email Is Null Please Enter Email";
	public static final String EXCEPTION609 = "Given Id For Deletion Is Null Please Send Some Id";
	public static final String DOCTORDELETE ="This Doctor is Deleted";
	public static final String EXCEPTIONEMAILVALIDATION ="Please Enter The Valid Email Id";
	public static final String INVALIDUSER="User Not Found";
	public static final String VALIDUSER="User Found";
	public static final String CAPTCHA_VALUE = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
	public static final String PATIENT_NOT_FOUND = "paitent not found";
	public static final String DOCTOR_NOT_FOUND = "doctor not found ";
	public static final String APPOINTMENT_NOT_FOUND = "appointment is empty";
	public static final String EMPTY_FILE = "file is empty";
	public static final String INVALID_EMAIL = "Inavalid email ";
	public static final String CAPTCHA_FIELD = "Captcha field not be null";
	public static final String OLD_PASSWORD_NOT_MATCH = "Old Password not match";
	public static final String NEW_PASSWORD_NOT_MATCH = "New Pawword and Confirm Password not matcha";
	public static final String PASSWORD_UPDATE = "Password successfully change";
	public static final String PASSWORD_NOT_UPDATE = "Password not change";
	public static final String EMAIL_USE = "this email already exists";
	public static final String MOBILE_NUMBER_USE = "this mobile number already use, try to another mobile number";
	public static final String ADDRESS_NOT_FOUND = "current address is  not registerd";
	public static final String HOSPITAL_NAME_USE = "Hospital name already register";
	public static final String HOSPITAL_NOT_FOUND = "hospital id not found ";
	public static final String HOSPITAL_ADDRESSNOT_NOT_FOUND = "Hospital Address not found";
}